apiVersion: v1
kind: Service
metadata:
  name: bittrader-candle-api
  labels:
    app: candle-api
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: candle-api
  ports:
    - port: 80
      targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bittrader-candle-api
  labels:
    app: candle-api
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: candle-api
  template:
    metadata:
      labels:
        app: candle-api
        tier: backend
    spec:
      containers:
        - name: candle-api
          image: ghcr.io/ken-tunc/bittrader/bittrader-candle-api
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: MYSQL_HOST
              value: bittrader-mysql
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: bittrader-backend-config
                  key: mysql_database
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: bittrader-backend-config
                  key: mysql_user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bittrader-backend-secret
                  key: mysql_password
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: bittrader-backend-config
                  key: time_zone
