apiVersion: v1
kind: Service
metadata:
  name: bittrader-mysql
  labels:
    app: mysql
    tier: backend
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bittrader-mysql-pv-claim
  labels:
    app: mysql
    tier: backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bittrader-mysql
  labels:
    app: mysql
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
        tier: backend
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          imagePullPolicy: Always
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: bittrader-backend-config
                  key: mysql_user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bittrader-backend-secret
                  key: mysql_password
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bittrader-backend-secret
                  key: mysql_root_password
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: bittrader-backend-config
                  key: mysql_database
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: bittrader-backend-config
                  key: time_zone
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: bittrader-mysql-pv-claim
