apiVersion: apps/v1
kind: Deployment
metadata:
  name: bittrader-order-scheduler
  labels:
    app: order-scheduler
    tier: backend
spec:
  selector:
    matchLabels:
      app: order-scheduler
  template:
    metadata:
      labels:
        app: order-scheduler
        tier: backend
    spec:
      containers:
        - name: order-scheduler
          image: ghcr.io/ken-tunc/bittrader/bittrader-order-scheduler
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: bittrader-backend-config
                  key: time_zone
