apiVersion: v1
kind: Service
metadata:
  name: bittrader-web
  labels:
    app: web
    tier: backend
spec:
  type: LoadBalancer
  selector:
    app: web
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bittrader-web
  labels:
    app: web
    tier: backend
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
        tier: backend
    spec:
      containers:
        - name: web
          image: ghcr.io/ken-tunc/bittrader/bittrader-web
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: bittrader-backend-config
                  key: time_zone
