bittrader:
  strategy:
    strategy-candle-num: 300
    optimize-candle-num: 1000
    ema:
      default-short-time-frame: 7
      default-long-time-frame: 14
      short-time-frame-from: 5
      short-time-frame-to: 15
      long-time-frame-from: 12
      long-time-frame-to: 20
    macd:
      default-short-time-frame: 12
      default-long-time-frame: 26
      default-signal-time-frame: 9
      short-time-frame-from: 10
      short-time-frame-to: 15
      long-time-frame-from: 25
      long-time-frame-to: 30
      signal-time-frame-from: 5
      signal-time-frame-to: 10
    rsi:
      default-time-frame: 14
      default-buy-threshold: 20
      default-sell-threshold: 80
      time-frame-from: 10
      time-frame-to: 15
      buy-threshold-from: 20
      buy-threshold-to: 30
      sell-threshold-from: 70
      sell-threshold-to: 80
      threshold-step: 2
    bollinger-bands:
      default-time-frame: 20
      default-buy-k: 2.0
      default-sell-k: 1.0
      time-frame-from: 18
      time-frame-to: 22
      buy-k-from: 1.8
      buy-k-to: 2.2
      sell-k-from: 0.8
      sell-k-to: 1.2
      k-step: 0.1
