bittrader:
  strategy:
    max-candle-num: 300
    ema:
      default-short-time-frame: 7
      default-long-time-frame: 14
      short-time-frame-from: 5
      short-time-frame-to: 15
      long-time-frame-from: 12
      long-time-frame-to: 20
