bittrader:
  auth:
    username: ${BASIC_AUTH_USERNAME:user}
    password: ${BASIC_AUTH_PASSWORD:password}
    role: "USER"
    exclude-paths:
      - "/"
      - "/favicon.ico"
      - "/charts/**"
      - "/webjars/**"
      - "/actuator/**"
