spring:
  application:
    name: bittrader-web
  main:
    web-application-type: reactive
  profiles:
    group:
      prod:
        - auth
      local:
        - dev
        - auth
      test:
        - dev
    include:
      - management
      - webjars
