- op: add
  path: /spec/template/spec/containers/0/livenessProbe
  value:
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 15
    periodSeconds: 10
    timeoutSeconds: 5
- op: add
  path: /spec/template/spec/containers/0/readinessProbe
  value:
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 15
    periodSeconds: 10
    timeoutSeconds: 5
