apiVersion: v1
kind: Service
metadata:
  name: bittrader-phpmyadmin
  labels:
    app: phpmyadmin
    tier: frontend
spec:
  type: LoadBalancer
  selector:
    app: phpmyadmin
  ports:
    - port: 18080
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bittrader-phpmyadmin
  labels:
    app: phpmyadmin
    tier: frontend
    gke: spot
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
        tier: frontend
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin/phpmyadmin
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOST
              value: bittrader-mysql
            - name: PMA_USER
              valueFrom:
                configMapKeyRef:
                  name: bittrader-backend-config
                  key: mysql_user
            - name: PMA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bittrader-mysql-secret
                  key: mysql_password
            - name: PMA_ARBITRARY
              value: "1"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
