name: Build diagrams

on:
  push:
    paths:
      - 'docs/diagrams/**/*.py'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docs/diagrams

    steps:
    - uses: actions/checkout@v2
    - name: Setup Graphviz
      uses: ts-graphviz/setup-graphviz@v1
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install diagrams
    - name: Build diagrams
      run: |
        python3 *.py
    - name: Push diagrams
      run: |
        if ! git diff --quiet -- *.png; then
          git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add ./*.png
          git commit -m "[skip ci] Build diagrams."
          git push origin HEAD:${GITHUB_REF}
        fi
