spring:
  application:
    name: bittrader-candle-api
  main:
    web-application-type: reactive
  profiles:
    group:
      prod:
        - mysql
      local:
        - h2
        - dev
      test:
        - h2
        - dev
    include:
      - management
      - strategy
  lifecycle:
    timeout-per-shutdown-phase: 5s
server:
  shutdown: graceful
