spring:
  application:
    name: bittrader-candle-api
  main:
    web-application-type: none
  profiles:
    group:
      prod:
        - mysql
      local:
        - h2
      test:
        - h2
  rsocket:
    server:
      port: 8081
